### ISSUE TITLE
Error on test.py

### ISSUE THREAD

**Issue by ogiel** [Smyja/blackmaria#1]
Hey, 
Your project looks super interesting and I wanted to try it out right away. However, when I do a clean install and run the test script it throws:
`TypeError: BaseGPTIndex.__init__() got an unexpected keyword argument 'prompt_helper'`
From the line:
`index = GPTSimpleVectorIndex(documents,prompt_helper=prompt_helper)`
Which is in the night crawler.

I can also not find the prompt_helper arg for the GPTSimpleVectorIndex in the llama-gpt package. Maybe it has version compatibility issues? Or am I doing something strange here

**Comment by smyja** [comment]
> Hey, Your project looks super interesting and I wanted to try it out right away. However, when I do a clean install and run the test script it throws: `TypeError: BaseGPTIndex.__init__() got an unexpected keyword argument 'prompt_helper'` From the line: `index = GPTSimpleVectorIndex(documents,prompt_helper=prompt_helper)` Which is in the night crawler.
>I can also not find the prompt_helper arg for the GPTSimpleVectorIndex in the llama-gpt package. Maybe it has version compatibility issues? Or am I doing something strange here

Thanks for raising this issue, it was a compatibility problem. I have fixed it. uninstall and install it again to get the latest version.

**Comment by smyja** [comment]
Resolved
