### ISSUE TITLE
Output is not matching

### ISSUE THREAD

**Issue by aiplaybookin** [Smyja/blackmaria#2]
Outputs shown in readme is not matching after running the ```test.py``` present in example folder. 

Also results shown in readme is not correct as per web link e.g. 
"starring": [
        "Lottie Matthews", 
        "Vanessa Palmer",
        "Misty Quigley",
        "Shauna Sadecki",
        "Natalie Scatorccio",
        "Taissa Turner"
      ]

Above are wrong, sorry if I am being brutal.

**Comment by smyja** [comment]
> Outputs shown in readme is not matching after running the ```test.py``` present in example folder. 
> 
> Also results shown in readme is not correct as per web link e.g. 
> "starring": [
>         "Lottie Matthews", 
>         "Vanessa Palmer",
>         "Misty Quigley",
>         "Shauna Sadecki",
>         "Natalie Scatorccio",
>         "Taissa Turner"
>       ]
> 
> Above are wrong, sorry if I am being brutal.

Thanks, I am aware. This project is experimental, Large language models hallucinate a lot. Only use this for well structured pages. LLMs predict not search.
